### ISSUE TITLE
Not able to install tiny-cuda

### ISSUE THREAD

**Issue by gaurav00700** [tangtaogo/lidar-nerf#3]
Hello,

Thank you for the amazing work and sharing the code.
I am trying to setup the environment for reproducing the results but I am not able to install tiny-cuda.
I have installed the packages using requirements.txt 

My environment is as below:-

OS: ubuntu20.04
Python 3.8.18
pytorch 1.8.1+cu101
torch.version.cuda 10.1
cuda 10.1

I am getting below error.
Can you please help me with this ?

```
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects
(lidar_nerf) gaurav@dergbsl1024:/data_repo/gaurav/LidarDomainAdaptation/WIP/repo/nerf/lidar-nerf$ pip list | grep -i -E "cuda|torch"

```

**Comment by tangtaogo** [comment]
Hi, 
Thanks for your interest!

tiny-cuda-nn (option 1)
First, make sure CUDA version is the same CUDA as the one compiled PyTorch
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

tiny-cuda-nn (option 2)
git clone https://github.com/NVlabs/tiny-cuda-nn.git
cd tiny-cuda-nn
git submodule update --init --recursive
cd bindings/torch
python setup.py install

And you can refer to the official github https://github.com/NVlabs/tiny-cuda-nn for more information and possible solutions

**Comment by gaurav00700** [comment]
> Hi, Thanks for your interest!
> 
> tiny-cuda-nn (option 1) First, make sure CUDA version is the same CUDA as the one compiled PyTorch pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
> 
> tiny-cuda-nn (option 2) git clone https://github.com/NVlabs/tiny-cuda-nn.git cd tiny-cuda-nn git submodule update --init --recursive cd bindings/torch python setup.py install
> 
> And you can refer to the official github https://github.com/NVlabs/tiny-cuda-nn for more information and possible solutions

Hi,
Thank you for your reply.

I was able to install tiny-cuda-nn by following the steps mentioned by you and [nerfstudio ](https://github.com/nerfstudio-project/nerfstudio)

I followed the following steps:-
```
pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

conda install -c "nvidia/label/cuda-11.7.1" cuda-toolkit
pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```
