### ISSUE TITLE
About KITTI360

### ISSUE THREAD

**Issue by HBLT-hub** [tangtaogo/lidar-nerf#5]
Hello, thank you very much for making your work open source.

What is your codename in KITTI-360:

{
        "1538",
        "1728",
        "1908",
        "3353",
}

What sequence numbers do these code numbers represent in the kitti360 data set? Because I am currently downloading the kitti360 data set.

Thank you very much

**Comment by tangtaogo** [comment]
Hello,
The kitti360 dataset is not organized based on sequence numbers. To split the dataset, you can only do so after downloading the complete dataset from the official website. For specific details regarding frames, please refer to https://github.com/tangtaogo/lidar-nerf/blob/8083a1d74eef6e7dc91c65ed7aedc2b45a39f76c/preprocess/kitti360_to_nerf.py#L35
For other datasets, e.g., waymo, which is organized based on sequences, please refer to https://github.com/tangtaogo/alignmif.
