### ISSUE TITLE
Some questions about the kitti360 dataset

### ISSUE THREAD

**Issue by lipeng-gu** [tangtaogo/lidar-nerf#7]
Hi,

I'm very interested in your work, but I have some questions about the kitti360 dataset:

Were all the experiments in this paper conducted using scene 4950 from the sequence 2013_05_28_drive_0000 for both training and testing? Or were there other setups?
Besides configs/kitti360_4950.txt, how should the configuration files for other scenes be set, especially the parameters scale and offset?

**Comment by tangtaogo** [comment]
Hi,
Perhaps you have entered someone else's folder, and there are several scene configs in the configs folder of our code:
<img width="204" alt="image" src="https://github.com/tangtaogo/lidar-nerf/assets/49675059/419ec48c-80b3-4fe5-892b-52a614007395">
