### ISSUE TITLE
您好，关于kitti360数据集中的data_2d_raw分支

### ISSUE THREAD

**Issue by booker-max** [tangtaogo/lidar-nerf#8]
![image](https://github.com/tangtaogo/lidar-nerf/assets/74257220/3b7c28b1-666b-4694-9c37-9a8fa77d3c7b)
您好，我想问一下data_2d_raw和data_3d_raw是不是对应着perceptive images和Raw Velodyne Scans呢

**Comment by tangtaogo** [comment]
Yes
